#!/bin/bash

set -e

if [ ! -d ./html ]; then
  echo "First start? (y/n):"
  read conf
  if [ "$conf == y" ]; then
    chmod +x ./scripts/install.sh
    chmod +x ./scripts/apcon.sh
    ./scripts/install.sh
    else
    exit 1
  fi
fi
